title: Social Base
theme: minima
description: Digital resource for social science researchers
url: "https://social-base.github.io"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
